### ISSUE TITLE
HTTPS Everywhere incompatibility

### ISSUE THREAD

**Issue by Craftplacer** [tjhrulz/WebNowPlaying-BrowserExtension#39] opened 2019-11-24 13:53 UTC
I was trying to figure out why Firefox was making the extension's WebSocket connections into secure ones (causing the extension not to connect correctly to Rainmeter). After playing around, I found out that it was HTTPS Everything causing this, disabling it on for example SoundCloud seems to resolve issue but is there anything that can be done about it (except adding an exception for the current site)?

**Comment by tjhrulz** [comment] 2020-01-18 06:10
No unfortunately not that I am aware of. We would need a signed cert for the URL we are using and the issue is that to get a free one of those we would need to prove ownership of our URL......which is LOCALHOST.

Now as to who thought not to make an exception for connections that never leave your computer is another thing.

I tried at one point to have the Rainmeter plugin create a certificate authority on your computer and issue itself a cert but that sadly did not work. If you or anyone else has an idea to fix this and feel free to lead a hand.

I also am going to close this since it is technically covered in the scope of #7 




Edit: Also try maybe adding LOCALHOST or 127.0.0.1 as exceptions under HTTPS Everywhere, as that may work for all sites.

**Closed as completed by tjhrulz** 2020-01-18 06:10 UTC
